### ISSUE TITLE
New menu

### ISSUE THREAD

**Issue by phoenixmcallister** [cyanidee/snowflake#3]
Just saying if someone was to make a menu for this, then this will become a great base for beginners with some comments added too

**Comment by NullFlex** [comment]
maybe u can do this ))

**Comment by encode32** [comment]
You can actually make a simple menu with this base easily. Used this as base and like it.

![](https://i.imgur.com/WyckwYM.gif)

**Comment by HenkieHanker2** [comment]
@encode32 hey dude can i see how you did the name esp? because i cant figure out how to use the `interfaces::get().vgui_surface->draw_string()` 
thanks!

**Comment by HenkieHanker2** [comment]
and how is endscene index 9? i thought event manager was 9

**Comment by encode32** [comment]
@HenkieHanker2 
`			if ( options [ "var.espname" ].get<bool>( ) ) {
				if (interfaces::get().engine->get_player_info(i, &player_info)) {
					float nX = player_box.x + (player_box.w / 2);
					float nY = player_box.y - 15;

					wchar_t buf[128];
					std::string name = player_info.player_name,
						s_name = (name.length() > 0 ? name : "Empty");
					

					if (MultiByteToWideChar(CP_UTF8, 0, s_name.c_str(), -1, buf, 128) > 0){
						switch (entity->team()) {
						case 2:
							interfaces::get().vgui_surface->set_text_color(255, 200, 0);
							break;
						case 3:
							interfaces::get().vgui_surface->set_text_color(0, 200, 255);
							break;
						default:
							interfaces::get().vgui_surface->set_text_color(170, 170, 170);
							break;
						}

						int tw, th;
						interfaces::get().vgui_surface->get_text_size(esp_font, buf, tw, th);
						nX -= tw / 2;

						interfaces::get().vgui_surface->set_text_position(nX, nY);
						interfaces::get().vgui_surface->draw_string(buf, wcslen(buf));
					}
				}
			}`

**Comment by HenkieHanker2** [comment]
@encode32 thanks! can i get your surface class? cuz i am missing get_text_size, and can i get the player_info struct :D <3 ty

**Comment by cyanidee** [comment]
I am going to implement ImGui soon. Currently I am in rewriting stage. I am introducing reworked input system, ImGui as menu and probably some new features soon. Stay tuned.
