### ISSUE TITLE
m_viewPunchAngle and m_aimPunchAngle aren't being dumped by the netvar manager

### ISSUE THREAD

**Issue by atipls** [cyanidee/snowflake#4]
basically in the title, ive speent a good hour just trying to figure out why it doesnt work, i checked the values and they were stuck at 0.
i've checked the netvar dump and it basically did not contain the right offset 
netvar dump:
https://pastebin.com/raw/0bPVuP7d

**Comment by rishav394** [comment]
Sorry I am new. How to install this cheat?

**Comment by cyanidee** [comment]
@atipls Im going to write new (probably shitty and slow) netvar manager. Hopefully it will dump all netvars 😛

**Comment by atipls** [comment]
submitted a pr for a netvar manager that (hopefully) dumps every netvar
